### ISSUE TITLE
Add ability to order items by @access

### ISSUE THREAD

**Issue by Undistraction** [SassDoc/sassdoc#239]
It appears that there is no way to control the ordering of public/private entities in the docs.

 I have a few important mixins and a lot of (private) helper functions. Whilst I would like the private functions to appear in the docs, they currently appear before all the mixins which are the lib's API and much more important. I was hoping that the `access` item in the `.sassdocrc` would control the order as well as the visibility, but the order of items seems not to effect the order of the entities in the docs.

**Comment by FWeinb** [comment]
I think this should be solved by the default theme. The ordering of the data interface isn't defined in the API Spec of SassDoc and can change during minor or patch level updates. (It has append after the 2.0 release)

Moving this to the default theme is the right thing to do.

**Comment by HugoGiraudel** [comment]
I don't see how the theme will manage to do so.

**Comment by FWeinb** [comment]
By doing it like this https://github.com/SassDoc/sassdoc/issues/239#issuecomment-57992738

**Comment by valeriangalliat** [comment]
There's no point in doing this in the default theme, if we want to sort by `@access` for everyone we do it in the core like the other sort criteria.

Doing it in the theme is only useful if you want a *local* behavior change.

Ideally the sort criteria should be configurable but it's still not the case.

**Comment by HugoGiraudel** [comment]
My point, really.

**Comment by pascalduez** [comment]
And another `sassdoc-extras` filter ? 
It's really handy to be able to choose which filters/sorting to apply or not in a theme by using or not the relative functions. Although if we do it in core it won't be op-out ?

**Comment by valeriangalliat** [comment]
It's welcome as a filter, but the core still needs to sort the data so we have deterministic output.

Though, we need to think if we want the sort configuration to be at core's level or at the theme level… I think it would be acceptable if the default theme let users configure the sort order with a configuration option, but other themes could sort in a specific way using `extras` without letting users configure it. This way SassDoc core only cares about sorting for deterministic output, not user configuration.
